# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spaceship go boom!
# email: random.j.farmer (AT) gmail DOT com
description: > # this means to ignore newlines until "baseurl:"
  Exploding spaceships. Nasty bugs. Ventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://random-j-farmer.github.io" # the base hostname & protocol for your site

author: 
  name: Random J. Farmer
  # no thx to spam email

remote_theme: random-j-farmer/tagged-minima

header_pages:
 - about.md
 - decloaking-simulator.md

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  random-j-farmer

# Build settings
markdown: kramdown

plugins:
  - jekyll-remote-theme
