title: Spaceship go boom!
description: > # this means to ignore newlines until "baseurl:"
  In which the Intrepid Hero experiences Trials and Tribulations
  around Ishomilken, among them but not exlusively Exploding Spaceships,
  Nasty bugs, Funny Programming Jokes, and Ventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://random-j-farmer.github.io" # the base hostname & protocol for your site

author: 
  name: Random J. Farmer
  email: random.j.farmer (AT) gmail DOT com

remote_theme: random-j-farmer/tagged-minima

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  random-j-farmer
    discord: 
      name: "Random J Farmer#8197"
      id: 225720541057646592

# Build settings
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
